import {type Metadata} from 'next';
import React, {type ReactNode} from 'react';

import './globals.css';

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>): React.JSX.Element => (
  <html lang='en'>
    <body>{children}</body>
  </html>
);

export {metadata};
// eslint-disable-next-line import/no-default-export
export default RootLayout;
